
import React from 'react';
import EditIcon from '../icons/EditIcon';

interface GeneratedImageProps {
  image: string;
  onViewImage: (url: string) => void;
  onEditImage: (imageUrl: string) => void;
}

const GeneratedImage: React.FC<GeneratedImageProps> = ({ image, onViewImage, onEditImage }) => {
  return (
    <div className="relative group aspect-square">
      <img
        src={image}
        alt="Generated by Imagen"
        className="w-full h-full object-contain rounded-md bg-base-bg"
      />
      <div className="absolute inset-0 bg-black bg-opacity-60 flex items-center justify-center gap-6 opacity-0 group-hover:opacity-100 transition-opacity rounded-md">
        <button onClick={() => onViewImage(image)} className="text-white font-bold hover:underline">View</button>
        <button onClick={() => onEditImage(image)} className="text-white font-bold hover:underline flex items-center gap-1.5">
          <EditIcon className="w-5 h-5" />
          Edit
        </button>
      </div>
    </div>
  );
};

export default GeneratedImage;
